version: '3'
services:
  EpicTV:
    image: bestzwei/EpicTV:latest
    container_name: EpicTV
    ports:
      - "8899:80"
    environment:
      - PASSWORD=${PASSWORD:-111111}
    restart: unless-stopped
